### ISSUE TITLE
[REFACTOR] 정보 입력 화면 전체적인 코드 정리하기

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android_mail_12#3]
### 📌  내용
정보 입력 화면과 관련된 코드를 전체적으로 수정하고, 성능 개선하기

### 🛠 ToDo
- [x] 닉네임 규칙 지정하기
- [x] 이메일 규칙 지정하기
- [x] 닉네임 & 이메일 규칙을 정했을 경우에만, 'NEXT' 버튼이 활성화되도록 수정하기
- [x] 기기를 회전해도 닉네임 / 이메일 값이 유지되도록 수정하기
- [x] 'NEXT' 버튼이 활성화되면 사용자 정보 데이터를 다음 화면으로 전달하기
