### ISSUE TITLE
[REFACTOR] 홈 화면관련 코드 정리하기

### ISSUE THREAD

**Issue by aurora32s** [woowa-techcamp-2022/android_mail_12#6]
### 📌 내용
홈 화면에 보이는 상세 fragment를 제외한 홈 화면의 코드를 정리하고, 기본 요구사항 구현하기

### 🛠 ToDo
- [x] 코드 깔끔하게!🔥 정리하기
- [x] 백 버튼을 클릭했을 때, '정보 입력 화면'으로 돌아가는 것이 아닌, 앱 종료하기
- [x] 앱 종료 후, 재실행한 경우에는 '정보 입력 화면' 보여주기
- [x] 하단 탭에 Mail, Setting 2개로 구성되어 있고, 화면 회전 시에는 탭 선택 component를 좌측으로 이동시키기

**Comment by aurora32s** [comment]
### 🍿 더 수정해야 할 점
fragment backstack 관리와 관련해서 별도의 이슈를 만들어두고 기획을 완료한 이후에 구현해보자!
